{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mangrove.fullname" . }}-auth
  labels:
    {{- include "mangrove.labels" . | nindent 4 }}
type: Opaque
stringData:
  keys: {{ .Values.auth.keys | quote }}
{{- end }}
